# Generated by Django 4.2.5 on 2023-10-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_watchlist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
